config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'items/create'

  get 'items/new'

  get 'items/show'

  get 'welcome/index'
  
  root 'welcome#index'

  resources :users, only: [:index, :show] do
    resources :items
   end

  resources :items, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
    @items = Item.all
  end 

  def new
  	@item = Item.new
  end
  
  def create
    @item = current_user.items.build
    
    if @item.save
      flash[:notice] = "Item saved."
      redirect_to current_user
    else
      flash[:error] = "Error saving item. Please try again."
      render :new
    end
  end

  def destroy
  	@item.destroy
  	redirect_to root_path
  end

  private

  	def item_params
  		params.require(:item).permit(:user)
  	end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id] || current_user.id)
    @items = @user.items
  end

  

  def index
    @users = User.all
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.text_field :description, placeholder: "Enter New Item" %>
  <%= f.button :submit %>
<% end %>

app/views/items/_item.html.erb
<% if user_signed_in? %>
  <% @items.each do |item| %>
    <h3><%= item.title %></h3>
    <%= link_to "", items_show_path, method: :delete, class: 'glyphicon glyphicon-ok' %>
  <% end %>
 
<% end %>
<%= link_to "New Item", items_new_path %>

app/views/items/new.html.erb
<h1> Add New ToDo Item </h1>

<%= render partial: 'items/form' %>

app/views/items/show.html.erb
<h1>Your Items:</h1>

<%= render 'items/item' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <ul>
  <div class="container">
    <ul class="nav nav-tabs">

      <div class="pull-right user-info">
      <% if user_signed_in? %>
        Signed in as: <strong> <%= current_user.email%> </strong>
      <% end %>
    </ul>
    </div>
      <div class="container">
        <div class="row">
                <div class="span3"> <a href="/"> <h1> BLOCITOFF </h1> </a> </div>
                  <div class="navbar  pull-right">
                    <div class="navbar-inner">
                      <div class="nav-collapse collapse navbar-responsive-collapse">
                        <ul class="nav">
                          <li> <%= link_to 'Home', welcome_index_path %> </li>

                          <li> <%= link_to 'Users', users_path %> </li>

                          <% if user_signed_in? %>
                            <li> <%= link_to 'My ToDo List', items_show_path %> </li>
                            <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
                            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
                          <% else %>
                            <li> <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> </li>
                            <li> <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %> </li>
                          <% end %>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
        </div>
    </div>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
       
</body>
</html>

app/views/users/show.html.erb
<div class="row">
	<div class="page-header">
				<h1> <%= @user.email %>'s ToDo List </h1>
        <% if current_user == @user %>
        	<div class="col-md-6">
          		<%= render partial: 'items/form'%>
        	</div>
        <% end %>
	</div>
</div>
<div class="row">
	<%= render partial: 'items/item' %>
</div>

app/views/welcome/index.html.erb
<br/>
<div>
<p class="lead"> 
  Create a ToDo list where the items self-explode if not completed within 7 days. Prioritize!
</p>
<% if current_user %>
  <p>Welcome, <%= current_user.email %>!</p>
<% end %>
</div>